version: 0.2

env:
  variables:
    ECR_REPOSITORY_NAME: fluentbit  # リポジトリ名称

phases:
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - ECR_BASE="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      - aws ecr --region "${AWS_DEFAULT_REGION}" get-login-password | docker login --username AWS --password-stdin "${ECR_BASE}"
      - REPOSITORY_URI="${ECR_BASE}/${ECR_REPOSITORY_NAME}"
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)
  build:
    commands:
      - docker image build --platform=linux/arm64 --target ${TYPE} -t ${REPOSITORY_URI}:latest -t ${REPOSITORY_URI}:${IMAGE_TAG} -t ${REPOSITORY_URI}:${TYPE} .

  post_build:
    commands:
      - docker image push -a ${REPOSITORY_URI}
      - printf '{"name":"%s","ImageURI":"%s"}' "${ECR_REPOSITORY_NAME}" "${REPOSITORY_URI}:${IMAGE_TAG}" > imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - appspec.yaml
    - taskdef.json
