version: "3"

services:
  app:
    container_name: tomcat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # volumes:
    #   - ./webapps:/usr/local/tomcat/webapps
